// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```+
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf5NltRTa4CKuPrwK_ZmDWXslC_xmhzQI',
    appId: '1:1036526034031:web:fee5b9584fe59c7c42c19a',
    messagingSenderId: '1036526034031',
    projectId: 'dating-e2373',
    authDomain: 'dating-e2373.firebaseapp.com',
    databaseURL: 'https://dating-e2373-default-rtdb.firebaseio.com',
    storageBucket: 'dating-e2373.firebasestorage.app',
    measurementId: 'G-TL42ENTE69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8ajAhqAPJ6ZvT7u_DmFpi4KtS3dAkoLg',
    appId: '1:1036526034031:android:524c6cb8fcec6e7942c19a',
    messagingSenderId: '1036526034031',
    projectId: 'dating-e2373',
    databaseURL: 'https://dating-e2373-default-rtdb.firebaseio.com',
    storageBucket: 'dating-e2373.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdRgq8LCgwTVtKwqXsRVI8os76vzRoAlI',
    appId: '1:1036526034031:ios:3c87d16f0f5c5b9a42c19a',
    messagingSenderId: '1036526034031',
    projectId: 'dating-e2373',
    databaseURL: 'https://dating-e2373-default-rtdb.firebaseio.com',
    storageBucket: 'dating-e2373.firebasestorage.app',
    iosBundleId: 'com.example.nexora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf5NltRTa4CKuPrwK_ZmDWXslC_xmhzQI',
    appId: '1:1036526034031:web:6666a3b63c821a8542c19a',
    messagingSenderId: '1036526034031',
    projectId: 'dating-e2373',
    authDomain: 'dating-e2373.firebaseapp.com',
    databaseURL: 'https://dating-e2373-default-rtdb.firebaseio.com',
    storageBucket: 'dating-e2373.firebasestorage.app',
    measurementId: 'G-B51FGPYC03',
  );
}